const styles = {
  cardGridProps: {
    container: true,
    item: true,
    mobileSmall: true,
    boxSizing: 'border-box',
    alignItems: 'center',
    justifyContent: 'center',
    height: 'auto',
    color: 'white',
    rowGap: 3,
  },
  headerGridProps: {
    container: true,
    item: true,
    justifyContent: 'space-between',
    alignItems: 'center',
    mobileSmall: 12,
  },
  titleGridProps: {
    container: true,
    item: true,
    mobileSmall: 12,
    justifyContent: 'flex-start',
    alignItems: 'center',
    borderBottom: '1px solid #999',
    pb: 6,
  },
  titleProps: {
    fontFamily: 'Ethnocentric Regular Italics',
    fontSize: '80px',
    lineHeight: '90px',
    color: 'white',
    sx: {
      textShadow: '0px 7.169px 17.922px rgba(0, 0, 0, 0.83)',
    },
  },
  headerTextProps: {
    color: 'white',
    fontFamily: 'Satoshi Bold',
    fontSize: '24px',
    lineHeight: '160%',
  },
  profileGridProps: {
    container: true,
    item: true,
    mobileSmall: 12,
    justifyContent: 'center',
    alignItems: 'center',
    rowGap: 4,
    borderRadius: '24px',
    px: 7,
    py: 10,
    sx: {
      background: (theme) => theme.palette.Background.gradient.primary,
    },
  },
  profileHeaderGridProps: {
    item: true,
    container: true,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  profileHeaderProps: {
    color: 'white',
    fontFamily: 'Satoshi Black',
    fontSize: '32px',
    lineHeight: '160%',
  },
  profileFormGridProps: {
    item: true,
    container: true,
    justifyContent: 'flex-start',
    alignItems: 'center',
    mobileSmall: 12,
  },
  passwordGridProps: {
    container: true,
    item: true,
    mobileSmall: 12,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    borderRadius: '24px',
    px: 7,
    py: 6,
    sx: {
      background: (theme) => theme.palette.Background.gradient.primary,
    },
  },
  passwordHeaderProps: {
    color: 'white',
    fontFamily: 'Satoshi Black',
    fontSize: '32px',
    lineHeight: '160%',
    sx: {
      mb: '12px',
      width: '100%',
    },
  },
  passwordBodyProps: {
    color: (theme) => theme.palette.Greyscale[300],
    fontFamily: 'Satoshi Regular',
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0.2px',
    sx: {
      width: { mobileSmall: '75%', desktopMedium: '50%' },
      mb: 8,
    },
  },
  editAvatarGridProps: {
    item: true,
    container: true,
    justifyContent: 'flex-start',
    columnGap: 4,
    alignItems: 'center',
    mobileSmall: 12,
    mb: 1,
  },
  secondaryButtonProps: {
    extraProps: { padding: '2px', height: '54px' },
    extraButtonProps: {
      fontFamily: 'Satoshi Bold',
      fontSize: '14px',
      px: 5,
      py: 2,
      letterSpacing: '0.2px',
      minWidth: '160px',
    },
  },
};

export default styles;
