const styles = {
  mainGridProps: {
    position: 'relative',
    container: true,
    item: true,
    mobileSmall: true,
    justifyContent: 'center',
    alignItems: 'flex-start',
    px: 5,
    borderRadius: '20px',
    overflow: 'hidden',
    zIndex: 1,
    sx: {
      background: (theme) => theme.palette.Dark_Colors.Dark[2],
    },
  },
  headerGridProps: (isPractice) => ({
    position: 'relative',
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    mobileSmall: 12,
    mb: isPractice ? 0 : { mobileSmall: 4, desktopMedium: 10 },
    height: { mobileSmall: '15%', desktop: '18%' },
  }),
  chatGridProps: (isDone) => ({
    container: true,
    justifyContent: 'center',
    alignItems: 'flex-start',
    height: '100%',
    maxHeight: {
      mobileSmall: 'calc(580px + 15%)',
      desktop: 'calc(580px + 18%)',
    },
    rowGap: { tablet: '4px', desktopMedium: 2 },
    sx: {
      opacity: isDone ? '0.2' : 1,
    },
  }),
  questionGridProps: {
    position: 'absolute',
    bottom: 0,
    container: true,
    justifyContent: 'center',
    alignItems: 'center',
    mobileSmall: 12,
    py: { mobileSmall: '12px', desktopMedium: 2 },
    px: { mobileSmall: 2, desktopMedium: 3 },
    mx: 5,
    columnGap: 3,
    height: '100%',
    borderRadius: '20px',
    sx: {
      background: (theme) => theme.palette.Dark_Colors.Dark[1],
      transform: 'translateY(50%)',
    },
  },
  avatarGridProps: {
    item: true,
    container: true,
    mobileSmall: 'auto',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  avatarProps: {
    sx: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      width: { mobileSmall: '48px', desktop: '56px' },
      height: { mobileSmall: '48px', desktop: '56px' },
    },
  },
  textGridProps: {
    container: true,
    item: true,
    mobileSmall: true,
    height: '100%',
    textAlign: 'left',
    alignItems: 'center',
    rowGap: 2,
  },
  textProps: {
    color: 'white',
    fontFamily: 'Satoshi Bold',
    fontSize: {
      mobileSmall: '18px',
      desktopMedium: '20px',
      desktopLarge: '24px',
    },
    lineHeight: { mobileSmall: '30px', desktopMedium: '40px' },
  },
  avatarImgProps: {
    layout: 'fill',
    objectFit: 'cover',
  },
  imageGridProps: {
    position: 'absolute',
    top: 0,
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    mobileSmall: 12,
    height: { mobileSmall: '15%', desktop: '18%' },
  },
  bgImageProps: {
    placeholder: 'blur',
    layout: 'fill',
    priority: true,
    objectFit: 'cover',
    sx: {
      height: { mobileSmall: '15%', desktop: '18%' },
    },
  },
  optionsGridProps: (explanationOpened) => ({
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: explanationOpened ? 'flex-start' : 'center',
    mobileSmall: 12,
    height: explanationOpened ? '100%' : 'auto',
    mt: explanationOpened
      ? { mobileSmall: 6, desktop: 9 }
      : { mobileSmall: 3, desktopMedium: 0 },
    rowGap: { mobileSmall: '10px', desktop: '14px', desktopLarge: 3 },
  }),
  submitGridProps: {
    container: true,
    item: true,
    mobileSmall: 12,
  },
  submitProps: {
    fullWidth: true,
    variant: 'mission',
    sx: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: '100px',
      textTransform: 'capitalize',
      px: 3,
      py: 2,
      fontFamily: 'Satoshi Black',
      fontSize: '20px',
    },
  },
  workspaceGridProps: {
    sx: { position: 'absolute', width: '100%', height: '100%' },
  },
  masterChatSlideProps: (openChat) => ({
    direction: 'up',
    in: openChat,
    mountOnEnter: true,
    unmountOnExit: false,
    style: { display: !openChat ? 'none' : 'block' },
  }),
  chatSlideProps: (openChat) => ({
    direction: 'up',
    in: !openChat,
    mountOnEnter: true,
    unmountOnExit: true,
    timeout: { enter: 1000, exit: 1000 },
  }),
};

export default styles;
