import { REWARDS_IMG_URLS } from '@/assets/urls';

const REWARDS = {
  PREPAID_CARDS: {
    banner: REWARDS_IMG_URLS.PREPAID_CARDS.main,
    id: 'Prepaid Cards',
    cards: [
      {
        coins: '200K',
        title: 'Gift Card',
        value: 200,
        image: REWARDS_IMG_URLS.PREPAID_CARDS.cards.img1,
        id: 'Prepaid-GiftCard-0',
      },
      {
        coins: '150K',
        title: 'Gift Card',
        value: 150,
        image: REWARDS_IMG_URLS.PREPAID_CARDS.cards.img2,
        id: 'Prepaid-GiftCard-1',
      },
      {
        coins: '200K',
        title: 'Gift Card',
        value: 200,
        image: REWARDS_IMG_URLS.PREPAID_CARDS.cards.img3,
        id: 'Prepaid-GiftCard-2',
      },
      {
        coins: '350K',
        title: 'Gift Card',
        value: 350,
        image: REWARDS_IMG_URLS.PREPAID_CARDS.cards.img4,
        id: 'Prepaid-GiftCard-3',
      },
      {
        coins: '200K',
        title: 'Gift Card',
        value: 200,
        image: REWARDS_IMG_URLS.PREPAID_CARDS.cards.img5,
        id: 'Prepaid-GiftCard-4',
      },
      {
        coins: '500K',
        title: 'Gift Card',
        value: 500,
        image: REWARDS_IMG_URLS.PREPAID_CARDS.cards.img6,
        id: 'Prepaid-GiftCard-5',
      },
    ],
  },
  TECH_GIFTS: {
    banner: REWARDS_IMG_URLS.TECH_GIFTS.main,
    id: 'Tech Gifts',
    cards: [
      {
        coins: '500K',
        title: 'Gift Card',
        value: 500,
        image: REWARDS_IMG_URLS.TECH_GIFTS.cards.img1,
        id: 'TechGifts-GiftCard-0',
      },
      {
        coins: '300K',
        title: 'Gift Card',
        value: 300,
        image: REWARDS_IMG_URLS.TECH_GIFTS.cards.img2,
        id: 'TechGifts-GiftCard-1',
      },
      {
        coins: '800K',
        title: 'Gift Card',
        value: 800,
        image: REWARDS_IMG_URLS.TECH_GIFTS.cards.img3,
        id: 'TechGifts-GiftCard-2',
      },
      {
        coins: '300K',
        title: 'Gift Card',
        value: 300,
        image: REWARDS_IMG_URLS.TECH_GIFTS.cards.img4,
        id: 'TechGifts-GiftCard-3',
      },
      {
        coins: '200K',
        title: 'Gift Card',
        value: 200,
        image: REWARDS_IMG_URLS.TECH_GIFTS.cards.img5,
        id: 'TechGifts-GiftCard-4',
      },
      {
        coins: '200K',
        title: 'Gift Card',
        value: 200,
        image: REWARDS_IMG_URLS.TECH_GIFTS.cards.img6,
        id: 'TechGifts-GiftCard-5',
      },
    ],
  },
  STREAMING: {
    banner: REWARDS_IMG_URLS.STREAMING.main,
    id: 'Streaming Subscriptions',
    cards: [
      {
        coins: '20K',
        title: 'Gift Card',
        value: 20,
        image: REWARDS_IMG_URLS.STREAMING.cards.img1,
        id: 'Streaming-GiftCard-0',
      },
      {
        coins: '10K',
        title: 'Gift Card',
        value: 10,
        image: REWARDS_IMG_URLS.STREAMING.cards.img2,
        id: 'Streaming-GiftCard-1',
      },
      {
        coins: '30K',
        title: 'Gift Card',
        value: 30,
        image: REWARDS_IMG_URLS.STREAMING.cards.img3,
        id: 'Streaming-GiftCard-2',
      },
      {
        coins: '10K',
        title: 'Gift Card',
        value: 10,
        image: REWARDS_IMG_URLS.STREAMING.cards.img4,
        id: 'Streaming-GiftCard-3',
      },
      {
        coins: '20K',
        title: 'Gift Card',
        value: 20,
        image: REWARDS_IMG_URLS.STREAMING.cards.img5,
        id: 'Streaming-GiftCard-4',
      },
      {
        coins: '20K',
        title: 'Gift Card',
        value: 20,
        image: REWARDS_IMG_URLS.STREAMING.cards.img6,
        id: 'Streaming-GiftCard-5',
      },
    ],
  },
  GAMING_SUBS: {
    banner: REWARDS_IMG_URLS.GAMING_SUBS.main,
    id: 'Gaming Subscriptions',
    cards: [
      {
        coins: '10K',
        title: 'Gift Card',
        value: 10,
        image: REWARDS_IMG_URLS.GAMING_SUBS.cards.img1,
        id: 'GamingSubs-GiftCard-0',
      },
      {
        coins: '20K',
        title: 'Gift Card',
        value: 20,
        image: REWARDS_IMG_URLS.GAMING_SUBS.cards.img2,
        id: 'GamingSubs-GiftCard-1',
      },
      {
        coins: '20K',
        title: 'Gift Card',
        value: 20,
        image: REWARDS_IMG_URLS.GAMING_SUBS.cards.img3,
        id: 'GamingSubs-GiftCard-2',
      },
      {
        coins: '40K',
        title: 'Gift Card',
        value: 40,
        image: REWARDS_IMG_URLS.GAMING_SUBS.cards.img4,
        id: 'GamingSubs-GiftCard-3',
      },
      {
        coins: '60K',
        title: 'Gift Card',
        value: 60,
        image: REWARDS_IMG_URLS.GAMING_SUBS.cards.img5,
        id: 'GamingSubs-GiftCard-4',
      },
      {
        coins: '30K',
        title: 'Gift Card',
        value: 30,
        image: REWARDS_IMG_URLS.GAMING_SUBS.cards.img6,
        id: 'GamingSubs-GiftCard-5',
      },
    ],
  },
  GAMING_CREDS: {
    banner: REWARDS_IMG_URLS.GAMING_CREDS.main,
    id: 'Gaming Credits',
    cards: [
      {
        coins: '75K',
        title: 'Gift Card',
        value: 75,
        image: REWARDS_IMG_URLS.GAMING_CREDS.cards.img1,
        id: 'GamingCreds-GiftCard-0',
      },
      {
        coins: '50K',
        title: 'Gift Card',
        value: 50,
        image: REWARDS_IMG_URLS.GAMING_CREDS.cards.img2,
        id: 'GamingCreds-GiftCard-1',
      },
      {
        coins: '35K',
        title: 'Gift Card',
        value: 35,
        image: REWARDS_IMG_URLS.GAMING_CREDS.cards.img3,
        id: 'GamingCreds-GiftCard-2',
      },
      {
        coins: '100K',
        title: 'Gift Card',
        value: 100,
        image: REWARDS_IMG_URLS.GAMING_CREDS.cards.img4,
        id: 'GamingCreds-GiftCard-3',
      },
      {
        coins: '30K',
        title: 'Gift Card',
        value: 30,
        image: REWARDS_IMG_URLS.GAMING_CREDS.cards.img5,
        id: 'GamingCreds-GiftCard-4',
      },
      {
        coins: '50K',
        title: 'Gift Card',
        value: 50,
        image: REWARDS_IMG_URLS.GAMING_CREDS.cards.img6,
        id: 'GamingCreds-GiftCard-5',
      },
    ],
  },
  AI_SUBS: {
    banner: REWARDS_IMG_URLS.AI_SUBS.main,
    id: 'AI Subscriptions',
    cards: [
      {
        coins: '20K',
        title: 'Gift Card',
        value: 20,
        image: REWARDS_IMG_URLS.AI_SUBS.cards.img1,
        id: 'AISubs-GiftCard-0',
      },
      {
        coins: '10K',
        title: 'Gift Card',
        value: 10,
        image: REWARDS_IMG_URLS.AI_SUBS.cards.img2,
        id: 'AISubs-GiftCard-1',
      },
      {
        coins: '50K',
        title: 'Gift Card',
        value: 50,
        image: REWARDS_IMG_URLS.AI_SUBS.cards.img3,
        id: 'AISubs-GiftCard-2',
      },
      {
        coins: '20K',
        title: 'Gift Card',
        value: 20,
        image: REWARDS_IMG_URLS.AI_SUBS.cards.img4,
        id: 'AISubs-GiftCard-3',
      },
      {
        coins: '30K',
        title: 'Gift Card',
        value: 30,
        image: REWARDS_IMG_URLS.AI_SUBS.cards.img5,
        id: 'AISubs-GiftCard-4',
      },
      {
        coins: '40K',
        title: 'Gift Card',
        value: 40,
        image: REWARDS_IMG_URLS.AI_SUBS.cards.img6,
        id: 'AISubs-GiftCard-5',
      },
    ],
  },
  PROD_SUBS: {
    banner: REWARDS_IMG_URLS.PROD_SUBS.main,
    id: 'Productivity Subscriptions',
    cards: [
      {
        coins: '20K',
        title: 'Gift Card',
        value: 20,
        image: REWARDS_IMG_URLS.PROD_SUBS.cards.img1,
        id: 'Pro Subs-GiftCard-0',
      },
      {
        coins: '20K',
        title: 'Gift Card',
        value: 20,
        image: REWARDS_IMG_URLS.PROD_SUBS.cards.img2,
        id: 'Pro Subs-GiftCard-1',
      },
      {
        coins: '30K',
        title: 'Gift Card',
        value: 30,
        image: REWARDS_IMG_URLS.PROD_SUBS.cards.img3,
        id: 'Pro Subs-GiftCard-2',
      },
      {
        coins: '10K',
        title: 'Gift Card',
        value: 10,
        image: REWARDS_IMG_URLS.PROD_SUBS.cards.img4,
        id: 'Pro Subs-GiftCard-3',
      },
      {
        coins: '40K',
        title: 'Gift Card',
        value: 40,
        image: REWARDS_IMG_URLS.PROD_SUBS.cards.img5,
        id: 'Pro Subs-GiftCard-4',
      },
      {
        coins: '40K',
        title: 'Gift Card',
        value: 40,
        image: REWARDS_IMG_URLS.PROD_SUBS.cards.img6,
        id: 'Pro Subs-GiftCard-5',
      },
    ],
  },
  ENGINEERING_CREDS: {
    banner: REWARDS_IMG_URLS.ENGINEERING_CREDS.main,
    id: 'Engineering Credits',
    cards: [
      {
        coins: '5M',
        title: 'Gift Card',
        value: 5000,
        image: REWARDS_IMG_URLS.ENGINEERING_CREDS.cards.img1,
        id: 'ENG-Creds-GiftCard-0',
      },
      {
        coins: '1M',
        title: 'Gift Card',
        value: 1000,
        image: REWARDS_IMG_URLS.ENGINEERING_CREDS.cards.img2,
        id: 'ENG-Creds-GiftCard-1',
      },
      {
        coins: '2M',
        title: 'Gift Card',
        value: 2000,
        image: REWARDS_IMG_URLS.ENGINEERING_CREDS.cards.img3,
        id: 'ENG-Creds-GiftCard-2',
      },
      {
        coins: '900K',
        title: 'Gift Card',
        value: 900,
        image: REWARDS_IMG_URLS.ENGINEERING_CREDS.cards.img4,
        id: 'ENG-Creds-GiftCard-3',
      },
      {
        coins: '500K',
        title: 'Gift Card',
        value: 500,
        image: REWARDS_IMG_URLS.ENGINEERING_CREDS.cards.img5,
        id: 'ENG-Creds-GiftCard-4',
      },
      {
        coins: '5M',
        title: 'Gift Card',
        value: 5000,
        image: REWARDS_IMG_URLS.ENGINEERING_CREDS.cards.img6,
        id: 'ENG-Creds-GiftCard-5',
      },
    ],
  },
  FASHION_CARDS: {
    banner: REWARDS_IMG_URLS.FASHION_CARDS.main,
    id: 'Fashion Cards',
    cards: [
      {
        coins: '150K',
        title: 'Gift Card',
        value: 150,
        image: REWARDS_IMG_URLS.FASHION_CARDS.cards.img1,
        id: 'Fashion Cards-GiftCard-0',
      },
      {
        coins: '75K',
        title: 'Gift Card',
        value: 75,
        image: REWARDS_IMG_URLS.FASHION_CARDS.cards.img2,
        id: 'Fashion Cards-GiftCard-1',
      },
      {
        coins: '200K',
        title: 'Gift Card',
        value: 200,
        image: REWARDS_IMG_URLS.FASHION_CARDS.cards.img3,
        id: 'Fashion Cards-GiftCard-2',
      },
      {
        coins: '300K',
        title: 'Gift Card',
        value: 300,
        image: REWARDS_IMG_URLS.FASHION_CARDS.cards.img4,
        id: 'Fashion Cards-GiftCard-3',
      },
      {
        coins: '50K',
        title: 'Gift Card',
        value: 50,
        image: REWARDS_IMG_URLS.FASHION_CARDS.cards.img5,
        id: 'Fashion Cards-GiftCard-4',
      },
      {
        coins: '200K',
        title: 'Gift Card',
        value: 200,
        image: REWARDS_IMG_URLS.FASHION_CARDS.cards.img6,
        id: 'Fashion Cards-GiftCard-5',
      },
    ],
  },
  MUNCHIES: {
    banner: REWARDS_IMG_URLS.MUNCHIES.main,
    id: 'Munchies',
    cards: [
      {
        coins: '25K',
        title: 'Gift Card',
        value: 25,
        image: REWARDS_IMG_URLS.MUNCHIES.cards.img1,
        id: 'Munchies-GiftCard-0',
      },
      {
        coins: '15K',
        title: 'Gift Card',
        value: 15,
        image: REWARDS_IMG_URLS.MUNCHIES.cards.img2,
        id: 'Munchies-GiftCard-1',
      },
      {
        coins: '20K',
        title: 'Gift Card',
        value: 20,
        image: REWARDS_IMG_URLS.MUNCHIES.cards.img3,
        id: 'Munchies-GiftCard-2',
      },
      {
        coins: '10K',
        title: 'Gift Card',
        value: 10,
        image: REWARDS_IMG_URLS.MUNCHIES.cards.img4,
        id: 'Munchies-GiftCard-3',
      },
      {
        coins: '25K',
        title: 'Gift Card',
        value: 25,
        image: REWARDS_IMG_URLS.MUNCHIES.cards.img5,
        id: 'Munchies-GiftCard-4',
      },
      {
        coins: '50K',
        title: 'Gift Card',
        value: 50,
        image: REWARDS_IMG_URLS.MUNCHIES.cards.img6,
        id: 'Munchies-GiftCard-5',
      },
    ],
  },
};

export default REWARDS;
