const styles = {
  submitSuccessGridProps: {
    container: true,
    flexDirection: 'column',
    height: '100%',
    rowGap: 2,
  },
  backToSubmissionGridProps: {
    container: true,
    item: true,
    mobileSmall: 'auto',
    justifContent: 'flex-start',
    alignItems: 'center',
  },
  backToMissionButtonProps: {
    variant: 'outlined',
    sx: (theme) => ({
      borderColor: theme.palette.Common.White['100p'],
      borderRadius: '100px',
      fontFamily: 'Satoshi Bold',
      fontSize: '16px',
      textTransform: 'capitalize',
      color: theme.palette.Common.White['100p'],
      '&:hover': {
        background: theme.palette.Common.White['100p'],
        color: theme.palette.Dark_Colors.Dark[1],
        svg: {
          color: theme.palette.Dark_Colors.Dark[1],
        },
      },
    }),
  },
  successGridProps: {
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  successTextGridProps: {
    container: true,
    item: true,
    mobileSmall: true,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  successTitleProps: {
    fontFamily: 'Ethnocentric Regular Italics',
    fontSize: { laptop: '65px', desktop: '70px', desktopMedium: '75px' },
    color: 'white',
  },
  subtitleGridProps: {
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subtitleProps: {
    fontFamily: 'Satoshi Bold',
    fontSize: '18px',
    textAlign: 'center',
    color: 'white',
    width: { laptop: '40%', desktop: '30%', desktopMedium: '25%' },
  },
  taskTitleProps: {
    component: 'span',
    fontFamily: 'Satoshi Bold',
    fontSize: '18px',
    textAlign: 'center',
    sx: { color: (theme) => theme.palette.Background.green },
  },
  actionButtonsGridProps: {
    container: true,
    item: true,
    mobileSmall: 12,
    justifyContent: 'center',
    alignItems: 'center',
    columnGap: 3,
    mt: 4,
  },
  curlsGridProps: {
    position: 'absolute',
    top: '0px',
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nextTaskButtonProps: () => ({
    bgcolor: '#292B2F',
    inverted: true,
    text: 'Next Task',
    color: 'green',
    extraProps: {
      padding: '2px',
      height: { laptop: '40px', desktop: '42px', desktopMedium: '45px' },
      minWidth: { laptop: '100px', desktop: '120px', desktopMedium: '145px' },
    },
    extraButtonProps: {
      fontFamily: 'Satoshi Bold',
      fontSize: { laptop: '14px', desktop: '16px' },
      boxShadow: '0px 7px 25px #3A1E5D',
      px: { laptop: 2, desktop: 3, desktopMedium: 4 },
    },
  }),
  backToDashboardButtonProps: {
    variant: 'white',
    sx: {
      px: { laptop: 2, desktop: 3, desktopMedium: 4 },
      height: { laptop: '40px', desktop: '42px', desktopMedium: '45px' },
      fontSize: { laptop: '14px', desktop: '16px' },
      color: (theme) => theme.palette.Background.green,
      fontFamily: 'Satoshi Bold',
    },
  },
  innerSuccessGridProps: {
    position: 'relative',
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    rowGap: { laptop: 1, desktop: 2, desktopMedium: 3 },
  },
};

export default styles;
