const styles = {
  mainGridProps: {
    container: true,
    item: true,
    boxSizing: 'border-box',
    justifyContent: 'center',
    alignItems: 'flex-start',
    mobileSmall: 12,
    padding: { laptop: 3, desktop: 4, desktopMedium: 5 },
    columnGap: { laptop: 5, desktop: 6, desktopMedium: 7 },
    pb: 10,
    sx: {
      background: (theme) => theme.palette.Background.gradient.primary,
      borderRadius: '20px',
      boxSizing: 'border-box',
    },
  },
  topLayerGridProps: {
    container: true,
    item: true,
    justifyContent: 'space-between',
    mobileSmall: 12,
    mb: 4,
  },
  backButtonProps: {
    color: 'grey',
    text: 'Back Home',
    iconPlacement: 'left',
    extraProps: {
      padding: '2px',
      height: { laptop: '40px', desktop: '42px', desktopMedium: '45px' },
    },
    extraButtonProps: {
      fontFamily: 'Satoshi Bold',
      fontSize: { laptop: '14px', desktop: '16px' },
      px: { laptop: 2, desktop: 3, desktopMedium: 4 },
    },
  },
  otherLearnersGridProps: {
    container: true,
    item: true,
    mobileSmall: true,
    rowGap: { laptop: 4, desktop: 6 },
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  centerGridProps: {
    position: 'relative',
    container: true,
    item: true,
    flexDirection: 'column',
    mobileSmall: true,
    maxWidth: '33% !important',
    rowGap: { laptop: 4, desktop: 6 },
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rightGridProps: {
    container: true,
    item: true,
    flexDirection: 'column',
    mobileSmall: true,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topCenterGridProps: {
    position: 'relative',
    container: true,
    item: true,
    flexDirection: 'column',
    mobileSmall: true,
    minHeight: '230px',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    rowGap: { laptop: 2, desktop: 3, desktopMedium: 4 },
    overflow: 'hidden',
  },
  overviewGridProps: {
    container: true,
    item: true,
    mobileSmall: true,
    overflow: 'hidden',
    sx: {
      display: '-webkit-box',
      WebkitLineClamp: 2,
      WebkitBoxOrient: 'vertical',
    },
  },
  overviewProps: {
    fontFamily: 'Satoshi Regular',
    fontSize: { laptop: '14px', desktop: '15px', desktopLarge: '18px' },
    color: 'white',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    sx: {
      display: '-webkit-box',
      WebkitLineClamp: 2,
      WebkitBoxOrient: 'vertical',
    },
  },
  seeMoreProps: {
    fontFamily: 'Satoshi Bold',
    fontSize: { laptop: '14px', desktop: '15px', desktopLarge: '18px' },
    color: (theme) => theme.palette.Background.green,
    sx: {
      '&:hover': {
        cursor: 'pointer',
      },
    },
  },
  seeMoreTooltipProps: {
    disableFocusListener: true,
    disableHoverListener: true,
    disableTouchListener: true,
    slotProps: {
      tooltip: {
        sx: {
          bgcolor: (theme) => theme.palette.Dark_Colors.Dark[2],
          color: 'rgba(255, 255, 255, 0.87)',
          boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.3)',
          maxWidth: 450,
          px: 2,
          py: 1,
          borderRadius: '18px',
          fontFamily: 'Satoshi Regular',
          fontSize: {
            laptop: '14px',
            desktop: '16px',
            desktopLarge: '18px',
          },
          lineHeight: '20px',
        },
      },
    },
  },
  bottomCenterGridProps: {
    container: true,
    item: true,
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
    columnGap: { laptop: 1, desktop: 2 },
  },
  titleProps: {
    fontFamily: 'Satoshi Bold',
    fontSize: { laptop: '32px', desktop: '40px', desktopMedium: '44px' },
    color: 'white',
    lineHeight: '48px',
  },
  chipGridProps: {
    container: true,
    item: true,
    mobileSmall: 'auto',
    justifyContent: 'flex-start',
    alignItems: 'center',
    columnGap: { laptop: 1, desktop: 1.5, desktopMedium: 2 },
  },
  detailsGridProps: {
    container: true,
    item: true,
    mobileSmall: true,
    justifyContent: 'center',
    alignItems: 'center',
  },
  learnersDetailsGridProps: {
    container: true,
    item: true,
    justifyContent: 'flex-start',
    alignItems: 'center',
    columnGap: 3,
    mobileSmall: 'auto',
  },
  avatarIconsGroup: {
    container: true,
    item: true,
    alignItems: 'center',
    justifyContent: 'center',
    mobileSmall: 'auto',
    sx: {
      button: {
        marginLeft: '-8px',
      },
    },
  },
  learnersGridProps: {
    container: true,
    item: true,
    mobileSmall: 'auto',
    alignItems: 'flex-start',
    flexDirection: 'column',
  },
  learnerNumbersProps: {
    fontFamily: 'Satoshi Bold',
    fontSize: { laptop: '18px', desktop: '20px' },
    color: 'white',
  },
  otherLearnersProps: {
    fontFamily: 'Satoshi Regular',
    fontSize: { laptop: '14px', desktop: '16px' },
    color: 'white',
  },
  imageGridProps: {
    position: 'relative',
    minHeight: '230px',
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    mobileSmall: 12,
    sx: { borderRadius: '20px', overflow: 'hidden' },
  },
  statisticChipProps: {
    extraChipGridProps: { height: '28px', px: 1 },
    extraChipProps: {
      fontSize: '14px !important',
      backgroundColor: 'transparent',
    },
  },
  statsGridProps: {
    container: true,
    item: true,
    mobileSmall: 'auto',
  },
  statsContainerGridProps: {
    container: true,
    item: true,
    alignItems: 'center',
    justifyContent: 'center',
    mobileSmall: 'auto',
    columnGap: { laptop: 1.5, desktop: 3 },
  },
  chipProps: {
    sx: {
      fontFamily: { laptop: 'Satoshi Medium', desktopMedium: 'Satoshi Bold' },
      fontSize: { laptop: '12px', desktop: '14px', desktopMedium: '15px' },
    },
  },
  enrollButtonProps: () => ({
    color: 'green',
    extraProps: {
      padding: '2px',
      height: { laptop: '40px', desktop: '42px', desktopMedium: '45px' },
      minWidth: { laptop: '100px', desktop: '120px', desktopMedium: '145px' },
    },
    extraButtonProps: {
      fontFamily: 'Satoshi Bold',
      fontSize: { laptop: '14px', desktop: '16px' },
      boxShadow: '0px 7px 25px #3A1E5D',
      px: { laptop: 2, desktop: 3, desktopMedium: 4 },
    },
  }),
  learnMoreButtonProps: {
    color: 'green',
    textColor: 'black',
    extraProps: {
      padding: '2px',
      height: { laptop: '40px', desktop: '42px', desktopMedium: '45px' },
    },
    extraButtonProps: {
      fontFamily: 'Satoshi Bold',
      fontSize: { laptop: '14px', desktop: '16px' },
      px: { laptop: 2, desktop: 3, desktopMedium: 4 },
    },
  },
  continueButtonProps: {
    variant: 'white',
    sx: {
      px: { laptop: 2, desktop: 3, desktopMedium: 4 },
      height: { laptop: '40px', desktop: '42px', desktopMedium: '45px' },
      fontSize: { laptop: '14px', desktop: '16px' },
      color: (theme) => theme.palette.Background.green,
      fontFamily: 'Satoshi Bold',
    },
  },
  registeredButtonProps: {
    variant: 'white',
    registered: 'true',
    sx: {
      px: { laptop: 2, desktop: 3, desktopMedium: 4 },
      boxShadow: '0px 7px 25px #002D20',
      height: { laptop: '40px', desktop: '42px', desktopMedium: '45px' },
      fontSize: { laptop: '14px', desktop: '16px' },
      fontFamily: 'Satoshi Bold',
    },
  },
  finishedButtonProps: {
    variant: 'white',
    registered: 'true',
    sx: {
      px: { laptop: 2, desktop: 3, desktopMedium: 4 },
      height: { laptop: '40px', desktop: '42px', desktopMedium: '45px' },
      fontSize: { laptop: '14px', desktop: '16px' },
      color: (theme) => theme.palette.Greyscale[498],
      fontFamily: 'Satoshi Bold',
    },
  },
  completedButtonProps: {
    variant: 'white',
    completed: 'true',
    sx: {
      px: { laptop: 2, desktop: 3, desktopMedium: 4 },
      height: { laptop: '40px', desktop: '42px', desktopMedium: '45px' },
      fontSize: { laptop: '14px', desktop: '16px' },
      fontFamily: 'Satoshi Bold',
    },
  },
  challengeInfoTitleProps: {
    color: 'white',
    fontFamily: 'Satoshi Regular',
    fontSize: { laptop: '16px', desktop: '18px' },
    sx: {
      width: '100%',
      py: { laptop: 1.5, desktop: 2 },
    },
  },
  lessonsInfoProps: {
    fontFamily: 'Satoshi Medium',
    color: 'white',
    fontSize: { laptop: '16px', desktop: '18px' },
    sx: {
      width: '100%',
      py: { laptop: 1.5, desktop: 2 },
    },
  },
  dividerProps: {
    sx: { borderColor: 'white', width: '100%' },
  },
  boldTitleProps: {
    style: {
      fontFamily: 'Satoshi Medium',
      fontSize: '18px',
      marginRight: '8px',
    },
  },
  rightTopGridProps: {
    container: true,
    item: true,
    flexDirection: 'column',
    mobileSmall: 12,
    minHeight: '230px',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  rightBottomGridProps: {
    container: true,
    item: true,
    flexDirection: 'column',
    mobileSmall: 12,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  challengeInfoTitleGridProps: {
    container: true,
    item: true,
    justifyContent: 'flex-start',
    alignItems: 'center',
    columnGap: 2,
  },
  logoProps: {
    layout: 'fill',
    objectFit: 'contain',
    alt: 'sponser_logo',
  },
  sponseredByProps: {
    fontSize: { laptop: '14px', desktopMedium: '16px' },
    color: (theme) => theme.palette.Greyscale[500],
  },
  sponserGridProps: {
    container: true,
    item: true,
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'relative',
    width: { laptop: 90, desktop: 110, desktopMedium: 120 },
    sx: { aspectRatio: '16 / 9' },
  },
};

export default styles;
