const ApplicationErrorStyle = {
  LogoImageGridProps: {
    container: true,
    item: true,
    mobileSmall: 'auto',
    position: 'relative',
    top: '-32px',
  },
  LogotitleGridProps: {
    container: true,
    item: true,
    mobileSmall: true,
    flexDirection: 'column',
  },
  LogotitleProps: {
    fontFamily: 'Ethnocentric Regular',
    fontSize: '32px',
    color: 'Black',
    position: 'relative',
    top: '-85px',
    left: '59px',
  },
  LogosubtitleProps: {
    fontFamily: 'Satoshi Bold',
    fontSize: '13.5px',
    color: '#AD83FF',
    textAlign: 'left',
    position: 'relative',
    top: '-95px',
    left: '59.5px',
  },
  LogocontentGridProps: {
    position: 'fixed',
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    rowGap: 2,
    top: '40px',
    left: '-40px',
  },
  titleGridProps: {
    container: true,
    item: true,
    mobileSmall: 12,
    justifyContent: 'center',
  },
  subtitleProps: {
    color: 'black',
    textAlign: 'center',
    ontSize: { laptop: '30px', desktop: '36px', desktopMedium: '40px' },
    lineHeight: '54px',
    position: 'relative',
    top: '381px',
    fontFamily: 'Satoshi Bold',
    fontSize: '40px',
    fontWeight: 700,
    letterSpacing: '-0.02em',
  },
  bodyProps: {
    position: 'relative',
    top: '387px',
    fontFamily: 'Satoshi Regular',
    fontSize: '24px',
    fontWeight: 400,
    lineHeight: '32.4px',
    letterSpacing: '-0.02em',
    textAlign: 'center',
  },
  radialBg1Props: {
    position: 'absolute',
    left: 0,
    width: '810px',
    height: '810px',
    sx: {
      opacity: 0.5,
      borderRadius: '655px',
      transform: 'translate(-25%, 0px)',
    },
  },
  radialBg2Props: {
    position: 'absolute',
    left: 0,
    width: '400px',
    height: '400px',
    sx: {
      opacity: 0.5,
      borderRadius: '655px',
      transform: 'translate(25%, -35%)',
    },
  },
  radialBg3Props: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: '600px',
    height: '600px',
    sx: {
      opacity: 0.5,
      borderRadius: '655px',
      transform: 'translate(35%, 10%)',
    },
  },
  star1Props: {
    position: 'relative',
    color: '#5522FF',
    top: '100px',
    left: '10px',
  },
  star2Props: {
    position: 'relative',
    top: '5px',
    left: '430px',
  },
  star3Props: {
    position: 'relative',
    top: '165px',
    left: '459px',
  },
  NetworkLogo: {
    position: 'relative',
    top: '200px',
    left: '40px',
  },
  buttonGridProps: {
    position: 'relative',
    container: true,
    item: true,
    mobileSmall: 12,
    justifyContent: 'center',
    top: '250px',
  },
  buttonProps: {
    variant: 'contained',
    sx: {
      px: 5,
      py: '26px',
      borderRadius: '100px',
      textTransform: 'capitalize',
      fontSize: '18px',
      fontFamily: 'Satoshi Bold',
      lineHeight: '20px',
      bgcolor: '#1D1A2E',
      ':hover': {
        bgcolor: '#242038',
      },
    },
  },
  submitButtonProps: {
    color: 'purple',
    inverted: true,
    extraProps: {
      padding: '2px',
      height: { laptop: '54px', desktopMedium: '60px' },
      width: 'auto',
    },
    extraButtonProps: {
      fontFamily: 'Satoshi Bold',
      fontSize: '16px',
      px: 4,
    },
  },
};
export default ApplicationErrorStyle;
