const NetworkErrorStyle = {
  // Logo Grid Props
  LogoImageGridProps: {
    container: true,
    item: true,
    xs: 'auto',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  LogocontentGridProps: {
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    top: '40px', // Adjust if necessary for vertical centering
  },
  mainGridProps: {
    container: true,
    item: true,
    xs: 12,
    justifyContent: 'center',
    alignItems: 'center',
    style: {
      height: '100vh', // Full viewport height
      backgroundColor: '#ffffff', // White background
      overflow: 'hidden', // Prevent content overflow
    },
  },
  mainContentGridProps: {
    container: true,
    item: true,
    xs: 10,
    md: 8,
    xl: 5,
    justifyContent: 'center',
    alignItems: 'center',
    direction: 'column',
    rowGap: 1,
  },
  TopcontentGridProps: {
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    height: 'auto',
    rowGap: 2,
  },
  BottomcontentGridProps: {
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    height: 'auto',
    rowGap: 2,
  },
  IconcontentGridProps: {
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    height: 'auto',
    rowGap: 2,
  },
  NetworkLogo: {
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    left: '0px',
  },
  radialBg1Props: {
    position: 'absolute',
    left: 0,
    width: '810px',
    height: '810px',
    sx: {
      opacity: 0.5,
      borderRadius: '655px',
      transform: 'translate(-25%, 0px)',
    },
  },
  radialBg2Props: {
    position: 'absolute',
    left: 0,
    width: '400px',
    height: '400px',
    sx: {
      opacity: 0.5,
      borderRadius: '655px',
      transform: 'translate(25%, -35%)',
    },
  },
  radialBg3Props: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: '600px',
    height: '600px',
    sx: {
      opacity: 0.5,
      borderRadius: '655px',
      transform: 'translate(35%, 10%)',
    },
  },
  sectionGridProps: {
    container: true,
    item: true,
    xs: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconsGridProps: {
    container: true,
    columnGap: { xs: 0, md: 10 },
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleGridProps: {
    container: true,
    item: true,
    xs: 12,
    justifyContent: 'center',
  },
  subtitleProps: {
    color: 'black',
    textAlign: 'center',
    fontFamily: 'Satoshi Bold',
    fontWeight: 700,
    fontSize: { laptop: '30px', desktop: '36px', desktopMedium: '40px' },
    lineHeight: '54px',
  },
  bodyGridProps: {
    container: true,
    item: true,
    xs: 9,
    xl: 8,
    justifyContent: 'center',
    alignItems: 'center',
    mb: 3,
    direction: 'column',
  },
  bodyProps: {
    color: 'black',
    textAlign: 'center',
    fontFamily: 'Satoshi Regular',
    fontWeight: 400,
    fontSize: '22px',
    lineHeight: '32.4px',
    width: '612px',
    height: '96px',
    letterSpacing: '-2%',
  },
  buttonGridProps: {
    container: true,
    item: true,
    xs: 12,
    justifyContent: 'center',
    top: '10px',
  },
  buttonProps: {
    variant: 'contained',
    sx: {
      px: 5,
      py: '26px',
      borderRadius: '100px',
      textTransform: 'capitalize',
      fontSize: '18px',
      fontFamily: 'Satoshi Bold',
      lineHeight: '20px',
      bgcolor: '#1D1A2E',
      ':hover': {
        bgcolor: '#242038',
      },
    },
  },
  star1Props: {
    position: 'relative',
    color: '#5522FF',
    top: '-470px',
    left: '-130px',
  },
  star2Props: {
    position: 'relative',
    bottom: '540px',
    left: '430px',
  },
  star3Props: {
    position: 'relative',
    bottom: '700px',
    left: '400px',
    top: '30px',
  },
};

export default NetworkErrorStyle;
