const pageNotFoundStyles = {
  // logo for the 404 page
  LogoImageGridProps: {
    container: true,
    item: true,
    mobileSmall: 'auto',
    position: 'relative',
    top: '-32px',
  },
  LogotitleGridProps: {
    container: true,
    item: true,
    mobileSmall: true,
    flexDirection: 'column',
  },
  LogotitleProps: {
    fontFamily: 'Ethnocentric Regular',
    fontSize: '32px',
    color: 'Black',
    position: 'relative',
    top: '-85px',
    left: '59px',
  },
  LogosubtitleProps: {
    fontFamily: 'Satoshi Bold',
    fontSize: '13.5px',
    color: '#AD83FF',
    textAlign: 'left',
    position: 'relative',
    top: '-95px',
    left: '59.5px',
  },
  LogocontentGridProps: {
    position: 'fixed',
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    rowGap: 2,
    top: '40px',
    left: '-40px',
  },
  mainGridProps: {
    position: 'relative',
    top: '35px',
    container: true,
    item: true,
    mobileSmall: 12,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    overflow: 'hidden',
    maxWidth: { laptop: '1450px' },
    sx: {
      borderRadius: '22px',
    },
  },
  mainContentGridProps: {
    position: 'relative',
    container: true,
    item: true,
    mobileSmall: 10,
    desktop: 8,
    desktopExtraLarge: 5,
    justifyContent: 'center',
    rowGap: 1,
  },
  TopcontentGridProps: {
    position: 'relative',
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    height: 'auto',
    rowGap: 2,
  },
  BottomcontentGridProps: {
    position: 'relative',
    container: true,
    top: '-18px',
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    height: 'auto',
    rowGap: 2,
  },
  IconcontentGridProps: {
    position: 'relative',
    container: true,
    item: true,
    justifyContent: 'center',
    alignItems: 'center',
    height: 'auto',
    rowGap: 2,
  },
  radialBg1Props: {
    position: 'absolute',
    left: 0,
    width: '810px',
    height: '810px',
    sx: {
      opacity: 0.5,
      borderRadius: '655px',
      transform: 'translate(-25%, 0px)',
    },
  },
  radialBg2Props: {
    position: 'absolute',
    left: 0,
    width: '400px',
    height: '400px',
    sx: {
      opacity: 0.5,
      borderRadius: '655px',
      transform: 'translate(25%, -35%)',
    },
  },
  radialBg3Props: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: '600px',
    height: '600px',
    sx: {
      opacity: 0.5,
      borderRadius: '655px',
      transform: 'translate(35%, 10%)',
    },
  },
  sectionGridProps: {
    container: true,
    item: true,
    mobileSmall: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconsGridProps: {
    container: true,
    columnGap: { mobileSmall: 0, desktop: 10 },
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleGridProps: {
    container: true,
    item: true,
    mobileSmall: 12,
    justifyContent: 'center',
  },
  subtitleProps: {
    color: 'black',
    textAlign: 'center',
    fontFamily: 'Satoshi Bold',
    weight: 700,
    fontSize: { laptop: '30px', desktop: '36px', desktopMedium: '40px' },
    lineHeight: '54px',
  },
  bodyGridProps: {
    container: true,
    item: true,
    mobileSmall: 9,
    desktopMedium: 8,
    justifyContent: 'center',
    mb: 3,
  },
  bodyProps: {
    position: 'relative',
    top: '18px',
    color: 'black',
    textAlign: 'center',
    fontFamily: 'Satoshi Regular',
    Weight: 400,
    fontSize: '22px',
    lineHeight: '32.4px',
    width: '612px',
    Hieght: '96px',
    letter: '-2%',
  },
  buttonGridProps: {
    position: 'relative',
    container: true,
    item: true,
    mobileSmall: 12,
    justifyContent: 'center',
    top: '10px',
  },
  buttonProps: {
    variant: 'contained',
    sx: {
      px: 5,
      py: '26px',
      borderRadius: '100px',
      textTransform: 'capitalize',
      fontSize: '18px',
      fontFamily: 'Satoshi Bold',
      lineHeight: '20px',
      bgcolor: '#1D1A2E',
      ':hover': {
        bgcolor: '#242038',
      },
    },
  },
  titleProps: {
    fontSize: { laptop: '105px', desktop: '125px', desktopMedium: '165px' },
    fontFamily: 'Ethnocentric Regular Italics',
    zIndex: 1,
    sx: {
      background: (theme) => theme.palette.primary.main,
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: '#856AFF',
    },
    position: 'relative',
    top: '58px',
  },
  submitButtonProps: {
    color: 'purple',
    inverted: true,
    extraProps: {
      padding: '2px',
      height: { laptop: '54px', desktopMedium: '60px' },
      width: 'auto',
    },
    extraButtonProps: {
      fontFamily: 'Satoshi Bold',
      fontSize: '16px',
      px: 4,
    },
  },
  star1Props: {
    position: 'relative',
    color: '#5522FF',
    top: '-470px',
    left: '-130px',
  },
  star2Props: {
    position: 'relative',
    bottom: '540px',
    left: '430px',
  },
  star3Props: {
    position: 'relative',
    bottom: '300px',
    left: '400px',
  },
  Meteor: {
    position: 'relative',
    top: '-455px',
    left: '52px',
    zIndex: 1,
  },
  Tail: {
    position: 'relative',
    top: '-500px',
    right: '14px',
    zIndex: 0,
  },
};

export default pageNotFoundStyles;
